[global.config]
  as = 65000
  router-id = "10.254.254.254"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.254.254.1"
    peer-as = 65002
  [neighbors.transport.config]
    passive-mode = false
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 255

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.254.254.251"
    peer-as = 65005
  [neighbors.transport.config]
    passive-mode = false
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 255

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.254.254.252"
    peer-as = 65005
  [neighbors.transport.config]
    passive-mode = false
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 255
